ALTER TABLE members
  ADD COLUMN IF NOT EXISTS is_area_rep TINYINT(1) NOT NULL DEFAULT 0 AFTER notes,
  ADD COLUMN IF NOT EXISTS is_committee TINYINT(1) NOT NULL DEFAULT 0 AFTER is_area_rep,
  ADD COLUMN IF NOT EXISTS committee_role VARCHAR(150) NULL AFTER is_committee;
